# TO USE CONFIG FILE: install.package('config')
#   https://cran.r-project.org/web/packages/config/index.html contains
#   package downloads if issues installing on MAC

### Start date for tool to run from ###
default:
  startDate:
    Month: "04"		  # MM
    Day: "03"			  # DD
    Year: "2016"		# YYYY
  
  endDate:
    Month: "10"		  # MM
    Day: "02"			  # DD
    Year: "2016"		# YYYY
  
  season:
    Months: ["03","04","05","06","07","08","09","10"]
  
  header: ["Date","Batter Name","Pitcher Name","Batter v Pitcher hand","Batter location","Pitcher v Batter hand","Pitcher location","At bats","Hit"]
  
  url:
    Base:"http://www.baseball-reference.com"
  
  TeamAbbrs:
    ARI: "Arizona Diamondbacks"
    ATL: "Atlanta Braves"
    BAL: "Baltimore Orioles"
    BOS: "Boston Red Sox"
    CHC: "Chicago Cubs"
    CHW: "Chicago White Sox"			
    CIN: "Cincinnati Reds"
    CLE: "Cleveland Indians"
    COL: "Colorado Rockies"
    DET: "Detroit Tigers"
    HOU: "Houston Astros"
    KCR: "Kansas City Royals"	
    LAA: ["Anaheim Angels", "Los Angeles Angels"]
    LAD: "Los Angeles Dodgers"
    FLA: "Miami Marlins"
    MIL: "Milwaukee Brewers"
    MIN: "Minnesota Twins"
    NYM: "New York Mets"				
    NYY: "New York Yankees"
    OAK: "Oakland Athletics"
    PHI: "Philadelphia Phillies"
    PIT: "Pittsburgh Pirates"
    SDP: "San Diego Padres"
    SFG: "San Francisco Giants"		
    SEA: "Seattle Mariners"
    STL: "St. Louis Cardinals"
    TBR: "Tampa Bay Rays"				
    TEX: "Texas Rangers"
    TOR: "Toronto Blue Jays"
    WSN: "Washington Nationals"
    
  StandardAbbrs:
    ARI: "ARI"
    ATL: "ATL"
    BAL: "BAL"
    BOS: "BOS"
    CHC: "CHC"
    CHW: "CHW"			
    CIN: "CIN"
    CLE: "CLE"
    COL: "COL"
    DET: "DET"
    HOU: "HOU"
    KCR: ["KCR", "KCA"]	
    LAA: ["ANA", "LAA"]
    LAD: "LAD"
    FLA: "FLA"
    MIL: "MIL"
    MIN: "MIN"
    NYM: "NYM"				
    NYY: "NYY"
    OAK: "OAK"
    PHI: "PHI"
    PIT: "PIT"
    SDP: "SDP"
    SFG: "SFG"		
    SEA: "SEA"
    STL: "STL"
    TBR: "TBR"				
    TEX: "TEX"
    TOR: "TOR"
    WSN: "WSN"
